### ISSUE TITLE
[Improvement] Xumm xApp loader till app calls ready()

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/Xaman-Issue-Tracker#438]
To allow for a consistent xApp loading experience (prevent loader flicker while xApp hydrates) we can show our own (improved) xApp loader screen;

- Icon (centered)
- xApp name (centered)
- Padding
- Loader (spinner, ..)
- [Reserved space for button, see below]

Behaviour stays as is, but developers can opt in to keeping the Xumm loader screen on top until their own app is done hydrating, at which point they call `ready()` on the Xumm SDK (postMessage to the app, like the others). Then the Xumm loader screen hides and the xApp becomes visible.

To allow for backwards compatibility, this is **opt in**. Developers can enable this in the Developer console on a per xApp basis, at which point they become responsible for calling the SDK's `ready()` method.

### Exception flows

1. The developer is working on the xApp and their app doesn't load, they need to be able to debug (e.g. reverse proxy 502 error or some other app error, preventing the SDK's `ready()` call being made).
2. The xApp takes very long to load or doesn't load at all: users are confronted with a long wait, and blame/contact Xumm (it's the Xumm screen) instead of the developer.

#### Proposed solutions:

- 1: With Xumm in Developer Mode, the Xumm loading screen shows a 'Proceed to xApp' button at the Xumm loader screen, below the spinner. This way the developer can dismiss the Xumm loader and view the underlying problem.
- 2: If the `ready()` method in the Xumm SDK isn't called within 6 (?) seconds, just like 1, a label + button is made visible: "xApp is slow to respond..." `[Contact developer]` » This button then opens the Support URL for the xApp as entered by the devs in the Developer Console. For older apps, where no support URL is entered in the developer console, we disable the option to opt in to Xumm xApp loader screen.

### Implementation

`app/xapp-launch` endpoint has enum `READY` https://h7cud66.dlvr.cloud/pasted_1.png. If the `READY` element is present:
- Show the loader till the `ready` postMessage is received through the SDK

**Comment by WietseWind** [comment]
Load timeout:

- X seconds: I think something min. 6, max 10, what do you think?
- I'll update the API output to contain the dev contact URL? https://h7cud66.dlvr.cloud/pasted_1.png
  `xappSupportUrl` ?

For older xApps it can be empty btw. In which case we hide the button, text would be:

#### Devs:
The xApp loader has not yet been resolved.
`[Btn: Force show xApp]`

#### Users:
The xApp has not been fully loaded (yet). If you run into trouble using this xApp, please contact the xApp developer.

`[Btn: Contact Developer] `

Button opens browser URL, but if URL = empty string button isn't there and the message is still relevant.

**Comment by N3TC4T** [comment]
Released as part of `v2.5`
