### ISSUE TITLE
[Bug] Collapse of encryption modal display

### ISSUE THREAD

**Issue by develoQ** [XRPL-Labs/Xaman-Issue-Tracker#454]
**Describe the bug**
Unnecessary Newline code is displayed on the screen when changing the passcode.

**Screenshots**

![IMG_4443](https://github.com/XRPL-Labs/Xaman-Issue-Tracker/assets/69445828/2c4a46f6-95ab-4746-a3cc-ccfa6302c931)

### Environment

* XUMM version: 2.6.0.5

**Comment by N3TC4T** [comment]
Thanks @develoQ.

Fixed in https://github.com/XRPL-Labs/Xaman-App/pull/89/commits/d8d87e1668b7ac4bfdd00eca1be17d411c39c344
