### ISSUE TITLE
[Translation] "Theme" doesn't support translation

### ISSUE THREAD

**Issue by tequdev** [XRPL-Labs/Xaman-Issue-Tracker#455]
**Describe the bug**

https://github.com/XRPL-Labs/Xaman-App/blob/80bd43d12d15659e0295d4193f62a8438f664f4d/src/screens/Settings/General/GeneralSettingsView.tsx#L266

### Environment

* XUMM version: [2.6.0.12]

**Comment by N3TC4T** [comment]
Thanks @tequdev, Fixed in https://github.com/XRPL-Labs/Xaman-App/pull/89/commits/aba76b24bdf1853a93a5538679ae961d8ee9bf2c
