### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by KoenPaas** [XRPL-Labs/Xaman-Issue-Tracker#456]
**Describe the bug**
Signing with multi sign xApp results in an unexpected error after Latest TestFlight version.

![IMG_4077](https://github.com/XRPL-Labs/Xaman-Issue-Tracker/assets/36813373/7a59de29-5ab1-4cc6-9131-8a78534ba9c8)
![IMG_4078](https://github.com/XRPL-Labs/Xaman-Issue-Tracker/assets/36813373/b782a35c-2ad0-45cb-ba8b-d69e4a33f60c)

To reproduce sign anything with the Multi Sign xApp using signer account array, cannot sign with any account.

**Comment by N3TC4T** [comment]
Thanks @KoenPaas, fixed 👍
