### ISSUE TITLE
[Feature] Filter by any token in transaction history

### ISSUE THREAD

**Issue by tequdev** [XRPL-Labs/Xaman-Issue-Tracker#462]
**Describe**
It would be useful to be able to filter by trustline deleted tokens in the transaction history filter function.

### Environment

What build of Xaman are you running? Please provide the full version (you can find it in Settings > Advanced).

* Xaman version: [2.6.0.18]

**Comment by N3TC4T** [comment]
Added the search for 'Currency' and 'Issuer' to the events list 👍 

<img width="250px" src="https://github.com/XRPL-Labs/Xaman-Issue-Tracker/assets/6250203/dba639aa-d2b6-4b4f-8c2b-d0c248478a4d" />
