### ISSUE TITLE
[Feature] Display HookReturnString on Hook execution error

### ISSUE THREAD

**Issue by tequdev** [XRPL-Labs/Xaman-Issue-Tracker#463]
**Describe the feature**
It would be user-friendly if a `HookReturnString` string is displayed on the screen when a `tecHOOK_REJECTED` error occurs on a Hooks enabled network.

<img width="320" src="https://github.com/XRPL-Labs/Xaman-Issue-Tracker/assets/69445828/00205773-b68f-4cdd-a8d0-6b2f59c40ca1" />

**Comment by WietseWind** [comment]
Great idea :D
