### ISSUE TITLE
[Bug] Events not updated when changing account

### ISSUE THREAD

**Issue by tequdev** [XRPL-Labs/Xaman-Issue-Tracker#464]
**Describe the bug**
Events not updated when changing accounts from long press on Home tab.

**To Reproduce**
1. Go to 'Event Tab'
2. Long pres 'Home Tap'
3. Change Account
4. Events remains as originally displayed

**Expected behavior**
The event page for the changed account is loaded and displayed.

### Environment

* Xaman version: [2.6.0.18]

* Manufacturer: [Apple]
* Model: [iPhone 15 Pro]
* OS version: [17.2.1]
* Platforms
  * [x] iOS
  * [ ] Android

**Comment by WietseWind** [comment]
Thanks for reporting! We noticed this ourselves as well, indeed, and are going to fix this in the upcoming release :)

**Comment by N3TC4T** [comment]
Thanks, Fixed in https://github.com/XRPL-Labs/Xaman-App/commit/59690fb1cc29406084577c6d7188dae71c1aca09
