### ISSUE TITLE
[Bug] Cannot open Xahau account in Explorer

### ISSUE THREAD

**Issue by tequdev** [XRPL-Labs/Xaman-Issue-Tracker#466]
**Describe the bug**
When opening a Xahau account in Explorer, the XRPL mainnet Explorer is opened instead of the Xahau Network Explorer.

https://xumm.app/explorer/21337/raZ8JfmTPpxCewWaAkzxDqKEd7nYfDuMsK

**Expected behavior**
The Website should switch networks according to the Network ID in the URL.
`https://xumm.app/explorer/21337/raZ8JfmTPpxCewWaAkzxDqKEd7nYfDuMsK`

**Screenshots**
<img width="320" src="https://github.com/XRPL-Labs/Xaman-Issue-Tracker/assets/69445828/5874c320-8891-490e-bffb-21ce025ae6ca" />

### Environment

What build of Xaman are you running? Please provide the full version (you can find it in Settings > Advanced).

* Xaman version: [2.6.0.18]

**Comment by N3TC4T** [comment]
Thanks @tequdev, we fixed this issue last week but indeed I forgot to inform you about this, I apologise for that.
