### ISSUE TITLE
Xaman force close in Dex Trade and Path Finding xapps 

### ISSUE THREAD

**Issue by Rand0mN3rd** [XRPL-Labs/Xaman-Issue-Tracker#487]
**Describe the bug**
Xaman force closes under 2 scenarios:
1) execution of transaction after path finding. 
2) pressing “get info” on an open limit order in Dex Trade

**To Reproduce**
Path finding force close 
1. Execute any path finding transaction. 
2. observe force close of app. 

Limit order “get info” force close
1. Go to dex trade
2. Execute any limit order that isn’t market and will not execute (outside of buy or sell trigger)
3. Wait for transaction to submit successfully 
4. Press “get info”
5. Observe force close of app

**Expected behavior**
For path finding execution I would expect the app to remain running and go back to the main page or back to pathfinding main menu.

for dex trade, I would expect to see order details when pressing “get info”

**Screenshots**
Videos attached. 

### Environment

What build of Xaman are you running? Please provide the full version (you can find it in Settings > Advanced).

* Xaman version: 2.6.0.18

What device are you running XUMM on?

* Manufacturer: Apple
* Model: iPhone 12 Max Pro
* OS version: iOS 17.3.1
* Platforms
  * [X] iOS

https://github.com/XRPL-Labs/Xaman-Issue-Tracker/assets/163242854/c7a847b7-d9d1-4f98-a2a0-d8c67bde4b12

### Additional context
Attach crash logs if available. Please ensure that these files do not contain any personal information.

**Comment by N3TC4T** [comment]
Thanks @Rand0mN3rd, we already aware of this issue and a fix https://github.com/XRPL-Labs/Xaman-App/commit/705ef4e54a1261dd13661c54879634dd8ee90986 is already in place for the next release.
