### ISSUE TITLE
[Bug] Wording incorrect

### ISSUE THREAD

**Issue by Ekiserrepe** [XRPL-Labs/Xaman-Issue-Tracker#514]
**Describe the bug**
While trying to activate a Tangem card on Xahau Testnet, the text talk about XRP Ledger instead of Xahau but uses XAH as currency correctly. "You imported a new account on the **XRP ledger.** The account is not activated. Account activation is a requirement on the **XRP ledger**.
To activate, you will have to make a first deposit of at least 1 XAH.·

**To Reproduce**
Activate Tangem Card account in Xahau Testnet and continue steps until screen shared below

**Expected behavior**
Seen Xahau as network in the wording instead o XRP Ledger

**Screenshots**
![IMG_3789](https://github.com/user-attachments/assets/66f38cd4-8b90-41b4-a80e-50473c13c624)

### Environment

What build of Xaman are you running? Please provide the full version (you can find it in Settings > Advanced).

* Xaman version: 3.0.1.1

What device are you running XUMM on?

* Manufacturer: Apple
* Model: iPhone 14 Pro
* OS version: 18.0.1
* Platforms
  * [ X] iOS
  * [ ] Android

**Comment by WietseWind** [comment]
@N3TC4T If we happen to have to send a new build to Apple for 3.0.2, let's try to squeeze this one in.

Thanks @Ekiserrepe!

**Comment by N3TC4T** [comment]
Solved in `2.0.3`
